services:
  server:
    image: pppltunnel:latest
    environment:
      MODE: server
      LISTEN: "0.0.0.0:34443"
      PASSWORD: changeme
      THREADS: 4
    ports:
      - "34443:34443"

  client:
    image: pppltunnel:latest
    environment:
      MODE: client
      LISTEN: "0.0.0.0:5201:iperf3:5201"
      CHAIN: "server:34443,changeme;copy"
      THREADS: 4
    ports:
      - "5201:5201"
    depends_on:
      - server

  iperf3:
    image: networkstatic/iperf3
    command: -s -p 5201

  iperf3-client:
    image: networkstatic/iperf3
    command: -c client -p 5201 -t 30
    depends_on:
      - client
      - iperf3
