FROM ubuntu:22.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libssl-dev \
    ruby \
    iperf3 \
    iproute2 \
    curl \
    python3 \
    gdb \
    ca-certificates \
    net-tools \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
